### ISSUE TITLE
Bot responds to its own messages

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#101]
When the bot sends messages, its handlers receive them afterwards. This makes the bot vulnerable to cyclic command responses (`!a -> !b`, `!b -> !a`), responding to itself for "spamming" (`!cactus twitter`, `Please do not post links.`, etc.), and so on.

**Comment by pylang** [comment]
@2Cubed Do message packets/json have something similar to an `author` key?  You could tell CB not to respond to `"self"` for example.

**Comment by 2Cubed** [comment]
@pylang They do! However, it's possible that the `author` is not *exactly* the same as the `self` written in config. (For example, Discord config is just an authkey, `NxWYTOQxdrweuoyxEFIOWjxzYxFOY3jY`-ish, which means that we can't really match it against that. Rather, we'd need to use some data that Discord responds with upon connection.)
It's not *impossible* to fix, but until the larger things are done, it's more work than it's worth to look into.

**Comment by pylang** [comment]
Well discerned good sir : )

**Comment by Innectic** [comment]
Fixed: https://github.com/CactusDev/CactusBot/pull/122
