### ISSUE TITLE
Target packet component type

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#113]
Should `target` be a packet component type? Currently, it is just part of a `text` packet.

```json
{
  "type": "target",
  "data": "%ARGS%",
  "text": "%ARGS%"
}
```

**Comment by Innectic** [comment]
Is there any use case for this? I couldn't think of one

**Comment by 2Cubed** [comment]
@Innectic The one that initially comes to mind is on the dashboard, highlighting targets or something.

**Comment by 2Cubed** [comment]
Sweet - I'll implement this Soon™. :ok_hand:

**Comment by 2Cubed** [comment]
Closing, in favor of #248.
