### ISSUE TITLE
Tag filter breaks if there are no arguments

### ISSUE THREAD

**Issue by Innectic** [CactusDev/CactusBot#146]
You can reproduce the error with:

```
!command add test %ARG1|tag%
!test
````

**Comment by 2Cubed** [comment]
If a tagged command is whispered to the bot, it appears in public chat, rather than being whispered to the user. Weird!

**Comment by Innectic** [comment]
I've been unable to reproduce this, if anyone else has any issues with this, please reopen the issue. 

http://i.imgur.com/54YvxXP.png
