### ISSUE TITLE
Default Arguments for Variables

### ISSUE THREAD

**Issue by Alkali-Metal** [CactusDev/CactusBot#148]
When assigning a variable in a custom command there is a possibility of it not receiving anything from the user command and some command look weird when those variables are missing, so it would be cool if there was a way to make a default which replaced empty variables and it was assigned on a per command basis so that you could have different defaults for each command.

```
[Alkali_Metal] !command add test Alkali is a %args[Metal!]%
[CactusBot] Command added!
[Alkali_Metal] !test potato!
[CactusBot] Alkali is a potato!
[Alkali_Metal] !test
[CactusBot] Alkali is a Metal!
```

**Comment by 2Cubed** [comment]
This has been implemented for a while; the issue was somehow left open, though.

```
!command add test Alkali is a %ARG1=Metal!%
```
