### ISSUE TITLE
Setup guide

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#172]
We need a walkthrough that explains how one would go about setting up CactusBot.

We should include both the way to set it up using our instance of CactusAPI and Sepal *and* instructions for setting up your own local API/Sepal versions.

**Comment by pylang** [comment]
Yes please.

**Comment by MrLotU** [comment]
@2Cubed I have vacation in 3 weeks (starting Saturday 18 Feb) and if someone explains me how to set up the bot I can try to get a manual setup

**Comment by QuirkySquid** [comment]
If we can agree on the process, I can make a video walkthrough of setting up CactusBot.
