### ISSUE TITLE
Join and leave notifications

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#173]
We already have notifications for follow, subscribe, and host. It should be fairly simple to add join and leave, as well. (**Off by default!**)

**Comment by alfw** [comment]
This is bad idea, if a bot send a notify when i join a channel it make me leave the channel. And not even talking or coming back.

**Comment by 2Cubed** [comment]
@alfw I would agree; it's not something I'd want running in my stream, personally. However, we've gotten requests for them, and we might as well make it an *option*. They *will* be off by default, though!
