### ISSUE TITLE
%ARGN% does not seem to work right now

### ISSUE THREAD

**Issue by AlphaBravoKilo** [CactusDev/CactusBot#183]
AlphaBravoKilo - `!raid TangoTek`
AlphaBot - `Awesome stream guys, thanks for watching! If you are up to watch some more livestreams, check out beam.pro/%ARG1% and share some Raid Cake with them! #ABKRaid`

Hmmm...?

**Comment by Innectic** [comment]
After debugging with you in your chat, it's been determined there was no bug here
