### ISSUE TITLE
Caching of all events

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#185]
Currently, only followers are cached. We need to cache all other events, as well.

We can cache in the `EventHandler` class itself. (No need for an external JSON file.) The main thing we need to protect against is rapid-fire notifications for button spamming.

**Comment by 2Cubed** [comment]
Prevents spam from rapid-fire following/unfollowing, hosting/unhosting, etc.

**Comment by MysticalMage** [comment]
I would work on this now (I heard caching), but I no longer have any idea how the CactusBot API works... as per #172
