### ISSUE TITLE
Rapid-hosting spam

### ISSUE THREAD

**Issue by AlphaBravoKilo** [CactusDev/CactusBot#186]
This happened in impulseSV's stream today

BeamBot- Andrew110 is now hosting you!
CactusBotAlpha- Thanks for the host Andrew110!
CactusBotAlpha- Thanks for the host Andrew110!
CactusBotAlpha- Thanks for the host Andrew110!
CactusBotAlpha- Thanks for the host Andrew110!
CactusBotAlpha- Thanks for the host Andrew110!

I was also able to replicate this. Might be a good idea to fix this.

**Comment by Alkali-Metal** [comment]
How did you replicate it? Or is this the "spammer" occasion?

**Comment by AlphaBravoKilo** [comment]
I replicated it by going to my own page and hosting from there. I sent a ticket to Beam about an issue with that, but surely there is a way to have a 10-15 minute timer on how often you are notified of one person hosting, right?

**Comment by AlphaBravoKilo** [comment]
So yes, it was a person spamming the Host feature on Beam

**Comment by Alkali-Metal** [comment]
Ah, yeah, there should be a *relatively* easy way to add a timer. AFAIK

**Comment by 2Cubed** [comment]
Merging into #185. :slightly_smiling_face:
