### ISSUE TITLE
Add filter that can be used with %COUNT% to by user execution

### ISSUE THREAD

**Issue by mwilkinson81** [CactusDev/CactusBot#189]
It'd be nice to have a filter like |user to use with the %count% variable to only count the number of times the user that ran the command had ran the command.

For Example:

EngineerWilky81: !command add userCount %name% ran this command %count|user% times.
CactusBotAlpha: command !userCount added.
EngineerWilky81: !userCount
CactusBotAlpha: EngineerWilky81 ran this command 1 times.
ImoutoKurpo: !userCount
CactusBotAlpha: ImoutoKurpo ran this command 1 times.

**Comment by 2Cubed** [comment]
Hmm... this would be "difficult", as we'd have to store a lot more than a simple integer.

Also, what happens in the following cases? (Who do the runs "belong to"?)
```
!command count potato +5
!command count potato -5
!command count potato =100
```

**Comment by Alkali-Metal** [comment]
Maybe you could reduce the amount of storage needed by instead implementing it per stream. (The filter makes it reset to 0 at the end of the stream) and then the `!command count` can just modify all instances of `%count%` including the per stream ones in the command, because I don't really see any purpose for per-user counts.

**Comment by 2Cubed** [comment]
Hmm... that's a good point, actually. What would be the purpose of per-user counters? cc: @mwilkinson81

**Comment by Alkali-Metal** [comment]
Like, I can see it being a neat little addition just to play around with a bit but I don't see any real purpose of it. :/

**Comment by Alkali-Metal** [comment]
I feel as though this could be obliterated due to the fact none of us can think of any purpose for this and @mwilkinson81 hasn't responded at all.

(But per stream `%COUNT%`s should exist, I would imagine something like the filter `%COUNT|stream%` or something like that.)

**Comment by 2Cubed** [comment]
Closing. (Can reopen if we discover a purpose for it later.)
