### ISSUE TITLE
Issues with repeats.

### ISSUE THREAD

**Issue by kondrik** [CactusDev/CactusBot#195]
I seem to be having no success with getting repeats working on [my channel](http://kondrik.com/stream?ghi).

When I tell the bot to add a repeat, it says it's added, but then doesn't list it.  If I try to re-add/edit the repeat I already added, the bot doesn't respond.  And if I try to remove the repeat, the bot says it doesn't exist.

![Screenshot1](https://cdn.discordapp.com/attachments/151580904177795073/270942981136187393/Repeats.png)

![Screenshot2](https://cdn.discordapp.com/attachments/151580904177795073/270525982576869376/CB-Repeat_bug.png)

**Comment by Innectic** [comment]
This seems to have been an issue with your api user. I've resolved this by recreating your user. Closing.
