### ISSUE TITLE
People in chat like to talk about d.va in Overwatch.  Cactusbot thinks it's a link.

### ISSUE THREAD

**Issue by EvilNotion** [CactusDev/CactusBot#198]
Would it be possible to add 'allowed' URLs? or for now, add a regexp scan for d.va ?

**Comment by Innectic** [comment]
Link whitelisting is a thing we plan to do, but we also have been thinking about adding a hard-whitelist for D.Va, since it's a silly thing to get the bot mad at you for

**Comment by Innectic** [comment]
Merging into #210

**Comment by 2Cubed** [comment]
Would like to keep this open, just so that we can ensure we add this specific link to the whitelist. (Will close after it's added to #210.) :slightly_smiling_face:

**Comment by Innectic** [comment]
This has been started on [feature/link-whitelisting](https://github.com/CactusDev/CactusBot/tree/feature/link-whitelisting)
