### ISSUE TITLE
User and Arg repeating?

### ISSUE THREAD

**Issue by misterjoker** [CactusDev/CactusBot#203]
Litterally exactly what I did.

misterjoker: !command add hug %USER% hugs %ARGS%
cactusbot:  Updated command !hug.
misterjoker: !hug @Alfred_E_Newman
cactusbot: misterjoker hugs @Alfred_E_Newman !hug @Alfred_E_Newman

**Comment by 2Cubed** [comment]
Good find! We definitely need to fix this.

**Comment by Innectic** [comment]
I seem to be unable to reproduce this bug. If you still have issues with it, reopen this issue :) 

http://i.imgur.com/3FexGjJ.png

**Comment by 2Cubed** [comment]
I was able to reproduce this.

![image](https://cloud.githubusercontent.com/assets/12002323/22856298/7ca3c314-f05c-11e6-8464-e04643739020.png)

**Comment by 2Cubed** [comment]
Testing shows that `.split()` appends the entire component to the end if the input ends with a *space*! :open_mouth: 

Working on a fix now.

**Comment by 2Cubed** [comment]
Closing this in favor of #222.

**Comment by 2Cubed** [comment]
Fixed in #222! :tada:
