### ISSUE TITLE
!config announce <state> toggle off not working

### ISSUE THREAD

**Issue by EvilNotion** [CactusDev/CactusBot#207]
Not sure which version of CactusBotAlpha ImpulseSV is running, but trying to turn off bot announcements isn't working.  No feedback to the command at all unless I don't fill it out properly, then it complains, but switching announcements to off (!config announce host toggle off ) isn't working.

<3 Keep up the awesome work guys!

**Comment by Alkali-Metal** [comment]
There is a fix for that already it just has not been rolled out yet. AFAIK :+1:

**Comment by Innectic** [comment]
Fixed in #219
