### ISSUE TITLE
Should we move Beam's Constellation interactions into Sepal?

### ISSUE THREAD

**Issue by Innectic** [CactusDev/CactusBot#211]
Moving these interactions into sepal would make the future alerts system much easier to actually handle, and would make event caching ( #185 ) not terribly hard to implement at all.

**Comment by 2Cubed** [comment]
I think we should keep all connections to services in the main bot. To me, it seems like much better encapsulation.

**Comment by Innectic** [comment]
@2Cubed How do we handle caching, and stream alerts then? The bot is not a suitable place for any of that

**Comment by 2Cubed** [comment]
@Innectic That's an excellent question.

I think for caching, we might just want to make an API request which does "some Redis stuff", and then make a quick request to check if the user is in the cache before sending the notification. (We could also add a way to clear the cache from the dashboard, for example.)

Not sure what you mean about "stream alerts".

**Comment by Innectic** [comment]
@2Cubed: Stream alerts = on stream alerts ("X PERSON JUST FOLLOWED OMGLOLYESTHANKSFORTHEFOLLOW")

**Comment by 2Cubed** [comment]
Ah, I see! Can't that just stay in the bot, like it is now? (Not talking about caching, BTW.) :slightly_smiling_face:

**Comment by Innectic** [comment]
I'm talking about *on stream*, not *in chat*

**Comment by 2Cubed** [comment]
@Innectic *Oh*, I see. Can't the bot just send "ohey, a follow happened" packets to Sepal, and then Sepal will distribute those to clients? :)

**Comment by Innectic** [comment]
@2Cubed The original intention for sepal was that the bot never interacts with it. The only time the bot was ever supposed to send something to sepal was authentication

**Comment by 2Cubed** [comment]
@Innectic Hmm... why? I don't see any reason why we shouldn't allow that... :thinking:
