### ISSUE TITLE
`!repeat list` not giving intervals

### ISSUE THREAD

**Issue by MrLotU** [CactusDev/CactusBot#216]
When you use `!repeat list` intervals are not given. This happens in version 0.3 but not in 0.4.

0.3:
<img width="310" alt="screen shot 2017-02-25 at 16 44 30" src="https://cloud.githubusercontent.com/assets/18392003/23332423/bb264206-fb79-11e6-952c-addb472d4fb9.png">

0.4:
<img width="322" alt="screen shot 2017-02-25 at 16 45 09" src="https://cloud.githubusercontent.com/assets/18392003/23332433/cafb6968-fb79-11e6-95e8-f44d5f8a7577.png">

0.3 is my own beam channel, 0.4 is Dukes channel

**Comment by Innectic** [comment]
Fixed in #218
