### ISSUE TITLE
Multiple service support

### ISSUE THREAD

**Issue by Innectic** [CactusDev/CactusBot#217]
Supporting multiple services at a time is an important thing to have. This will happen with #205, but figured there should be an issue for it too.

**Comment by 2Cubed** [comment]
What would this entail? Support for specific services (Discord, Twitch, etc.), or just a framework that is generalized for all services?

**Comment by Innectic** [comment]
A framework. The idea of 0.4 in the beginning was that it would be able to connect to anything with a socket. Websocket, TCP, UDP, or whatever.
