### ISSUE TITLE
Command handler

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#46]
Move existing command handling to a custom `Handler`.
- [x] Magic Commands
- [x] Custom Commands

**Comment by 2Cubed** [comment]
I think we should move as many custom commands as possible to the API, leaving only the essentials (`!help` only?) in the bot itself. It makes no sense for some commands to be part of the bot, and others part of the API. It would also allow for hotswapping, so that new builtins could be added via the API without the need for a full CactusBot update.

**Comment by 2Cubed** [comment]
Thanks to #61, we have decided to remove builtins. Done in 58a3a092daa3d4d83cf78b9a348907e35610329f.

**Comment by Innectic** [comment]
Custom commands have been completed, from what I've been told. Reopen this if I've heard wrong.

**Comment by 2Cubed** [comment]
@Innectic Custom commands are not yet complete. They will be *easy* to complete, but we need the API to support them, first.

**Comment by 2Cubed** [comment]
Works on `feature/custom-commands`. However, currently only stores text, not JSON packet.

**Comment by 2Cubed** [comment]
[Done!](https://github.com/CactusDev/CactusBot/blob/3a8de02626f1a05ce0b74dfd470ed611845079d6/cactusbot/handlers/command.py#L64) :ok_hand:
