### ISSUE TITLE
Logging handler

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#48]
Simple handler that logs packets to different debug levels.

- Simplified text (`Hello! :)`) to `INFO`
- Full packet to `DEBUG`

**Comment by Innectic** [comment]
What's the packet format, though? When I'm loggin the "basic" version, do I need to `join` the basic components (`link`, `emote`, `text`), or can I use something like `packet["message"]`?

**Comment by 2Cubed** [comment]
@Innectic It should be `''.join(chunk["text"] for chunk in packet)`.

**Comment by 2Cubed** [comment]
Hmm... `on_log`, interesting. I feel like logging should be catching all events, rather than just ones that are specifically sent as `log`s, however. That brings up an interesting point, though - maybe we should implement `on_anything` (possibly with a different name) that's a catchall for when the event isn't specified.

```python
def on_message(self, packet):
    self.logger.info(''.join(chunk["text"] for chunk in packet))
    self.logger.debug(packet)

def on_anything(self, *args):
    self.logger.debug(' '.join(map(str, args)))
```

When there's a `message` event, it gets sent to `on_message`, but other events (`on_follow`) will be sent to `on_anything`. Thoughts?

**Comment by Innectic** [comment]
@2Cubed I tried getting a `join` to work, but nothing I tried worked. Putting it into and "extended for-loop" fixed it. Feel free to give it a shot

**Comment by Innectic** [comment]
@2Cubed Hmm, that would work. I'll implement that real fast

**Comment by 2Cubed** [comment]
@Innectic [Continuing from](https://github.com/CactusDev/CactusBot/issues/44#issuecomment-250919923)

The logging handler is a low-level logger that just outputs what it reads. So, it would log `[Innectic] Hello!` and `{"user": "Innectic", "message": [{"type": "text", "text": "Hello!", "data": "Hello!"}]` to the console, on `INFO` and `DEBUG`, respectively.
The other handlers, though, can use their own loggers for more specific purposes. For example, the `CommandHandler` can log `/command/test returned 404` to `DEBUG`. Because each handler is initialized with its own logger (with name `__name__`), the logging output will show `DEBUG CommandHandler: debug message`, so we can tell what every handler is doing.

**Comment by 2Cubed** [comment]
Completed in d6d95bceaa8b62082a5043bd8bcfde480d4c91cc.
