### ISSUE TITLE
Beam parser

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#49]
`BeamParser` will parse incoming data from Beam to a standard packet format (#43).

**Comment by pylang** [comment]
Maybe you want an abstract `BaseParser` that can be subclassed to different services `BeamParser`, `TwitchParser`, etc.

**Comment by 2Cubed** [comment]
@pylang Yep, that's the plan! :smile:

**Comment by 2Cubed** [comment]
Currently able to parse most messages, as of 4e19a317a4ba9802634d69e260bebe40ff9ceca7.

Need to decide on how to separate functions that parse incoming packets and outgoing packets, and how to name/call them (similar to `on_`?).

**Comment by pylang** [comment]
You need to parse outgoing packets?

**Comment by 2Cubed** [comment]
Finished in a44ce6b73a5db1765af53acccdc9cea8a7a2614a, aside from needing to update the roles with accurate values (#54).
