### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#51]
We need unit tests.

**Comment by 2Cubed** [comment]
My preference would be to use [pytest](http://doc.pytest.org/en/latest/).

**Comment by Innectic** [comment]
It'd be cool to add a command line arg to cb. `python3 run.py --test` or something similar

**Comment by 2Cubed** [comment]
@Innectic Hmm... not sure. I think we should keep command-line arguments to bot features only (debug level, service toggling, etc.). The command that would be run is just `pytest`, though, so we could reconfigure Travis so install and run `pytest` on `master` and `develop` pull requests before merging. :smile:

**Comment by 2Cubed** [comment]
Started on `feature/unit-tests`. :tada:

**Comment by pylang** [comment]
command would be `py.test` I think.

**Comment by 2Cubed** [comment]
@pylang They're apparently both valid commands, and upon inspecting the source, they do exactly the same thing. According to their docs, it's `pytest`, so I guess I'll stick with that? /shrug

**Comment by pylang** [comment]
Thank goodness.  I think `py.test` is intuitive.  Thanks.

**Comment by pylang** [comment]
A suggestion for DRYer tests (and less typing), use a common `verify` function or method that calls repetitive code from source, example:

```python
class TestCommandHandler:

    command_handler = CommandHandler("TestChannel")

    def verify(msg, expected, *args, **kwargs)
        actual = self.command_handler.inject(MessagePacket(msg), *args, **kwargs).text
        assert actual == expected

    ...

    def test_inject_argn(self): 
        self.verify(
            "Let's raid %ARG1%!",
            "Let's raid GreatStreamer!",
            "raid", "GreatStreamer"
        )

        self.verify(
            "Let's raid %ARG1%! #%ARG2%",
            "Let's raid GreatStreamer! #ChannelRaid",
            "raid", "GreatStreamer", "ChannelRaid" 
        )

        self.verify(
            "Let's raid %ARG1%!",
            "Not enough arguments!",
            "raid"
        )

        self.verify(
            "This is the !%ARG0% command.", 
            "This is the !test command."
            "test", "arg1", "arg2"
        )

    ...


    def test_inject_channel(self):
        self.verify(
            "Welcome to %CHANNEL%'s stream'!",
            "Welcome to GreatStreamer's stream'!",
            "welcome", channel="GreatStreamer",
        )

        self.verify(
            "Welcome to %CHANNEL%'s stream'!",
            "Welcome to %CHANNEL%'s stream'!",
            "welcome",
        )
        
    ...
```

**Comment by 2Cubed** [comment]
@pylang Ooh... very good call.

**Comment by Innectic** [comment]
I started more of these on [feature/unit-testing](https://github.com/CactusDev/CactusBot/tree/fix/unit-testing)
