### ISSUE TITLE
Configurable event responses

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#53]
Responses for events (follow, subscribe, host) are hardcoded, and therefore not configurable. This should not be the case.

**Comment by Innectic** [comment]
This was never a "bug", it was just a feature we never really implemented

**Comment by 2Cubed** [comment]
@Innectic Fair enough. Didn't think `feature` really made sense, but in hindsight, I guess it makes more sense than `bug`.

**Comment by Innectic** [comment]
#59 is done as of today.

**Comment by Innectic** [comment]
This has been completed.
