### ISSUE TITLE
Role level map

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#54]
We need a standard mapping which defines what numerical role levels mean, qualitatively. The scale for role levels is 0-100.

Should include:
- [x] Channel Owner
- [x] Service Staff
- [x] Global Moderator
- [x] Moderator
- [x] Channel Subscriber
- [x] Service Subscriber
- [x] Standard User
- [x] Banned User

**Comment by 2Cubed** [comment]
Channel Owner should be `100`, Banned User should be `0`.

**Comment by Innectic** [comment]
Standard: 1
Sub: 10
Mod: 50
Global 100
Staff 100

**Comment by 2Cubed** [comment]
@Innectic Not sure I like Staff and Global Mod being `100`. You should be able to specify that you are the only one who can change something in the bot that even staff can't.

**Comment by Innectic** [comment]
@2Cubed I don't see a reason staff shouldn't be able to.

**Comment by 2Cubed** [comment]
@Innectic What about, for example, removing the bot from your channel? IMHO, that should be something only the owner should be able to do.

I think we should keep Staff/Global with high values, but not 100 - maybe, like, 95 and 90, respectively?

We should also keep gaps between these values, because on a service with custom roles especially, like Discord, you may want to put some roles between the "defaults".

**Comment by Innectic** [comment]
Hmm

**Comment by Alkali-Metal** [comment]
Suggestion for the Discord version: Maybe have the role values be set via something like `!power set [Value]` which would then set the role "level" and I agree with @2Cubed where there are situations that you do not want staff/global mods to be able to do something, for the most part, they should be able to do everything, but there should still be limits to a degree.

**Comment by 2Cubed** [comment]
@Alkali-Metal Allowing for role configuration would be difficult, just because of the way everything's written, but we could certainly give it a shot! :smile:

**Comment by 2Cubed** [comment]
Is it possible that we may not need a numerical scale, and that everything could be mapped to a specific set of *permissions*? Custom commands, for example, can currently be for Mod+, Sub+, or general use - would there be a case where people on a Discord server could only use a command if they were 72+, excluding role 71?

**Comment by 2Cubed** [comment]
Potentially:
```
- Channel Owner: 10
- Service Staff: 8
- Global Moderator: 7
- Moderator: 6
- Channel Subscriber: 4
- Service Subscriber: 2
- Standard User: 1
- Banned User: 0
```

**Comment by 2Cubed** [comment]
Done in #138.
