### ISSUE TITLE
Default streamer commands

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#58]
We should auto-generate a set of commands which would be helpful to streamers.

(For example, `!raid`.)

Which commands would be helpful?

**Comment by MindlessPuppetz** [comment]
!raid
!so / !shoutout
!raided
!social

**Comment by kz5ee** [comment]
!multi / !ms [_platform_][_target1_]...[_platform_][_targetN]

**Comment by 2Cubed** [comment]
@MindlessPuppetz 
- `!raid` and `!raided` - definitely.
- `!shoutout` - definitely.

We currently have `!social`, which queries the Beam API. Since our command system is becoming service-agnostic, though, we will need service-specific behaviors (#60).

**Comment by MindlessPuppetz** [comment]
My social links go beyond what beam provides... :P

**Comment by 2Cubed** [comment]
@KZ5EE Good call. How would this work, though? Using [multistream.xyz](multistream.xyz)?

- Our command system is becoming service-agnostic, but we will need to know the specific service that the streamer is using (#60). 
- What happens if the streamer is using a service that isn't supported by [multistream.xyz](multistream.xyz)?

**Comment by kz5ee** [comment]
@2Cubed multistream.xyz would be a good default.

If the multistream service isn't default, it can be changed in the config file with the URL arguments
Streaming platforms / !ms tags could be configured in a config file

I'll give it some more thought and get back to you.

**Comment by LauraDutra** [comment]
Agree with everyone on:
!raid
!shoutout or !so

!title and/or !game would be nice for mods to do transitions
!lurk is one that seems to be a standard action in most chats

**Comment by Innectic** [comment]
@LauraDutra `!lurk` and `!welcome` / `!raiders` should be broadcaster specific. Making that a default would be silly since basically every single broadcast would want something special

**Comment by 2Cubed** [comment]
@KZ5EE Thanks to suggestion by @artdude543, I think we should use http://multistream.me/. Very clean interface, easy to work with, and hosted by our partner, ExoZone! :smiley:

**Comment by 2Cubed** [comment]
@KZ5EE Thanks to suggestion by @alfw, I think we should use http://multistream.me/. Very clean interface, easy to work with, and hosted by our partner, ExoZone! :smiley:
