### ISSUE TITLE
Config integration with CactusAPI and Sepal

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#59]
Class designed to load and dynamically update configuration values.

Initially loads all configuration values from the API, and dynamically updates via Sepal.

One instance can be passed around and used throughout the bot. This way, all code related to config can be written once, in an organized fashion.

**Comment by Innectic** [comment]
Sepal side is done

**Comment by 2Cubed** [comment]
@Innectic This isn't done... we should only close after the Sepal client (in Python) is done and we're able to live update config values from it.

**Comment by 2Cubed** [comment]
Done in #115! :tada:

**Comment by Innectic** [comment]
Not yet it wasn't, silly cube! :P

**Comment by 2Cubed** [comment]
@Innectic Sorry, wrong issue! >.>
