### ISSUE TITLE
MessagePacket support within magic commands

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#66]
Currently, magic commands are based entirely around raw strings, which defeats the purpose of the typed `MessagePackets` in some sense. Magic commands should be able to use `MessagePackets` for added functionalities. (Emoji detection, tag usage, etc.)

**Comment by Innectic** [comment]
I thought they could return them already? I had some magic commands that did that, but, you changed them all to strings

**Comment by 2Cubed** [comment]
@Innectic They *can* return them. (I changed most back to raw strings, though, because `MessagePacket(raw_str)` all over the place is messy - only necessary for, say, `action=True`, `target="user"`, etc.) They don't *receive* them, though.

For example, in the `!cube` command, we need to be able to detect which arguments are emojis. [Currently](https://github.com/CactusDev/CactusBot/blob/5abf27821df8e38061b8ec36d70fd9231705f24f/cactusbot/commands/magic/cube.py#L35), we're using Beam-specific parsing, which is labeled as a `# HACK` - if we use the already-typed `MessagePacket`s, though, we could easily just use `if chunk["type"] == "emoji"`.

**Comment by 2Cubed** [comment]
We could potentially use another special kwarg-only argument, `raw`, to contain the raw `MessagePacket`.

**Comment by 2Cubed** [comment]
[Done.](https://github.com/CactusDev/CactusBot/blob/c5ec43506c3304ee8364f3305fcac284cda2ed03/cactusbot/handlers/command.py#L42)

We can consider a purely packet-based command system in the future; for now, though, this is :ok_hand:.
