### ISSUE TITLE
Targeted responses to custom commands

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#72]
Custom-added commands could respond to the user who ran the command through a targeted message (whisper/DM).

**Comment by Innectic** [comment]
I began this on https://github.com/CactusDev/CactusBot/tree/feature/whispered-commands

**Comment by 2Cubed** [comment]
Done and merged into `develop`. :tada:
https://github.com/CactusDev/CactusBot/blob/dfce4f42ba737eef64c76de7dd0aa4e4b580a4a8/cactusbot/handlers/command.py#L39
