### ISSUE TITLE
Improved targets

### ISSUE THREAD

**Issue by Innectic** [CactusDev/CactusBot#75]
We've always had basic targets like `%ARGS%`, but it would  be super cool to expand upon this using "angularish" _filters_. Example: convert the args to upper using: `%ARGS | upper%`

**Comment by 2Cubed** [comment]
We should also add defaults to `%ARGN%` targets!

```
!command add eat I'm eating a %ARG1=potato%!

!eat carrot
I'm eating a carrot!

!eat
I'm eating a potato!
```

**Comment by Innectic** [comment]
Sounds good to me!

**Comment by 2Cubed** [comment]
The entire target system should be generalized, so that defaults, modifiers, etc. work on non-`%ARG%` targets. (`%USER|upper%`, etc.)

**Comment by 2Cubed** [comment]
Success! :tada:
