### ISSUE TITLE
Move Beam connection to external package

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#88]
Should we move the Beam connection (`BeamAPI`, `BeamChat`, `BeamConstellation`) to an external package?

**Comment by pylang** [comment]
Aren't these a "service", or has that design changed?

**Comment by 2Cubed** [comment]
@pylang We're still going to be using our current service model. However, we could definitely move the code that handles the actual Beam connection *out* of the bot and into a separate Beam client package, and then just use that in CactusBot.

An example of this exact concept can be seen in our [discord](https://github.com/CactusDev/CactusBot/tree/9ca63df3f7110ef2f94cd0a9bd9dc1b23119a412/cactusbot/services/discord) service. We're using the `discord.py` package to handle all connection details, which is extremely convenient and much cleaner, IMHO.

**Comment by pylang** [comment]
So with this idea, would some services have external packages and others wouldn't?  Example, would twitch need a package?

**Comment by 2Cubed** [comment]
@pylang I'm thinking that we should keep all client packages out of the bot itself. In addition to the fact that it's much cleaner implementation-wise, this would allow others to use our code to create their own custom bots andclients.

**Comment by pylang** [comment]
Makes a ton of sense to me.

**Comment by 2Cubed** [comment]
@pylang Hmm... hadn't thought of that. I think the best course of action for adding Hitbox would be for us to create a generalized client package, `CactusDev/hitbox.py`, and then using that to add the service.

**Comment by pylang** [comment]
That's a idea.  So `hitbox.py` would be a different project in the GitHub organization.  Jupyter has this kind of setup for their extensions.  Something to think about:

- How would these "service packages" integrate with the core CB?   Would they be pip installable by the user, or batteries included when CB is installed (e.g. `run.py` fires up Beam, HitBox, Discord integration)?

**Comment by 2Cubed** [comment]
@pylang Each service would still need a `Handler` (`BeamHandler`, `DiscordHandler`, etc.), which are (currently) provided in `config.py`.
```python
SERVICE = BeamHandler(CHANNEL, handlers)
```

I believe `pip` has a way of installing different "parts" of the project:
```
pip install cactusbot
pip install cactusbot[service:beam]
```

We could use this to our advantage, along with some command-line arguments, to make the installation process really clean.
