### ISSUE TITLE
Custom social services

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/CactusBot#91]
Streamers have requested the ability to add custom services for `!social`. For example:

```
!social
Twitter: twitter.com/2CubedTech, GitHub: github.com/2Cubed

!social github
github.com/2Cubed
```

This makes sense, because we want to become service-agnostic, and our `!social` system currently depends on Beam.

**Comment by Innectic** [comment]
Done in https://github.com/CactusDev/CactusBot/pull/124
